name: Java CI with Maven

on:
  push:
    branches: [ "main" ]

jobs:

  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        repository: MindfulMichaelJames/star-wars
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - run: sudo npm install pm2 -g
    - run: npm install
    - run: npm run build --if-present
    - run: pm2 start npm -- start -p 3000
    - run: sudo apt-get update
    - run: sudo npm install -g puppeteer
    - run: google-chrome --version
    - uses: actions/checkout@v4
    - name: Set up JDK 22
      uses: actions/setup-java@v3
      with:
        java-version: '22'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - uses: actions/upload-artifact@v3
      with:
        name: public results
        path: target/report